###
GET http://localhost:5097/programadores

###
GET http://localhost:5097/programadores/4

###
POST http://localhost:5097/programadores
Content-Type: application/json

{
    "nombre": "Yuji",
    "apellido": "Itadori",
    "especialidad": "Ciberseguridad",
    "añosExperiencia": 1,
    "rango": "Junior"
}

###
PUT http://localhost:5097/programadores/2
Content-Type: application/json

{
    "nombre": "Yuta",
    "apellido": "Okkotsu",
    "especialidad": "Desarrollador Front-end",
    "añosExperiencia": 2,
    "rango": "Junior"
}

###
DELETE http://localhost:5097/programadores/4
